### ISSUE TITLE
Support for STDin and stDOut

### ISSUE THREAD

**Issue by Tsjippy** [armills/jsonrpc-async#8]
I am not sure, but does this also work for stdin?
I want to work with [this library](https://github.com/AsamK/signal-cli/wiki/JSON-RPC-service)  in a async way.

**Comment by emlove** [comment]
This library only supports JSON-RPC over HTTP. If you want to work with stdin/stdout, you could start with the `jsonrpc_base` library, and implement a stdin/stdout transport for it. If you start by forking https://github.com/emlove/jsonrpc-websocket/blob/master/jsonrpc_websocket/jsonrpc.py , you should be able to reimplement send_message to dump the message to stdout, and replace `_ws_loop` with a loop to read from stdin. The `jsonrpc_base` library can handle all the JSON bits, you'll just need to pass the serialized strings back and forth from stdin/stdout.
